### ISSUE TITLE
Node ? Really

### ISSUE THREAD

**Issue by raskyer** [thibaultgouin/ikone-studio#2]
Vous dites dans la doc :
Ouvrir l'invite de commande aller dans le projet et taper "npm install firebase --save"

Or :
1/ Le dossier est déjà présent dans le git (MDR) donc la commande au dessus est inutile
2/ A 0 , 0 moment vous n'utilisez de node module ... 0 !
Il n'y a pas de package.json, enfin 0 quoi ... votre git est lourd pour ... que dalle

**Comment by thibaultgouin** [comment]
dis le a Alex omg ! Je lui ai deja demandé si ca servait a quelque chose.

2016-07-05 13:01 GMT+02:00 Leakless notifications@github.com:

**Comment by alexb31** [comment]
Yo 

Pour ce qui est dans le doc, j'avais rajouté ça au tout début du projet quand je savais pas vraiment comment utiliser firebase donc je pensais qu'il fallait faire à chaque **firebase serve** (ah ah), du coup j'ai aussi supprimé le dossier node modules pour garder juste les fichier css et js dans le dossier dist situé dans la racine et ca fonctionne normalement après je sais pas si c'est la meilleure méthode :/

En tout cas, merci pour la remarque Vincent :)

**Comment by raskyer** [comment]
Okip,

Niveau racine et mvp supprimez le dossier node_module.
Ca rendra votre git beaucoup plus leger et donc plus facile à commit, pull etc ...

**Comment by alexb31** [comment]
Ok c'est ce que je viens de faire et pour l'instant pas d'erreur :) 

merci encore pour le conseil ;)
